//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class BangCapVienChuc
    {
        public int idBangCapVienChuc { get; set; }
        public int idVienChuc { get; set; }
        public int idLoaiBangCap { get; set; }
        public string tenBangCap { get; set; }
        public string coSoDaoTao { get; set; }
        public string bangNuocNgoai { get; set; }
        public string ngonNguDaoTao { get; set; }
        public string namCapBang { get; set; }
        public string linkFileDinhKem { get; set; }
    
        public virtual LoaiBangCap LoaiBangCap { get; set; }
        public virtual VienChuc VienChuc { get; set; }
    }
}
