//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class HopDongVienChuc
    {
        public HopDongVienChuc() { }

        public HopDongVienChuc(HopDongVienChuc hopDongVienChuc)
        {
            idHopDongVienChuc = hopDongVienChuc.idHopDongVienChuc;
            idVienChuc = hopDongVienChuc.idVienChuc;
            idLoaiHopDong = hopDongVienChuc.idLoaiHopDong;
            ngayBatDau = hopDongVienChuc.ngayBatDau;
            ngayKetThuc = hopDongVienChuc.ngayKetThuc;
            moTa = hopDongVienChuc.moTa;
            linkVanBanDinhKem = hopDongVienChuc.linkVanBanDinhKem;
            LoaiHopDong = hopDongVienChuc.LoaiHopDong;
            VienChuc = hopDongVienChuc.VienChuc;
        }

        public int idHopDongVienChuc { get; set; }
        public int idVienChuc { get; set; }
        public int idLoaiHopDong { get; set; }
        public Nullable<System.DateTime> ngayBatDau { get; set; }
        public Nullable<System.DateTime> ngayKetThuc { get; set; }
        public string moTa { get; set; }
        public string linkVanBanDinhKem { get; set; }
    
        public virtual LoaiHopDong LoaiHopDong { get; set; }
        public virtual VienChuc VienChuc { get; set; }
    }
}
